version: '3.8'

services:
  # Qdrant Vector Database (FREE)
  qdrant:
    image: qdrant/qdrant:latest
    container_name: knowledge-assistant-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # PostgreSQL (Optional - for storing query history)
  postgres:
    image: postgres:15-alpine
    container_name: knowledge-assistant-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=knowledge_assistant
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=devpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  qdrant_storage:
    driver: local
  postgres_data:
    driver: local

networks:
  default:
    name: knowledge-assistant-network

